# Site settings

# Base url
baseurl: "" # the subpath of your site, e.g. /blog

title: Octavia Shaw
email: shawoj93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website and Blog of Octavia Shaw! Here you will find projects that I am working on and blog posts things that interest me in the tech world.

url: "https://ojshaw.github.io"


# Outside links
twitter_username: coffeepops2
github_username:  ojshaw

# Build settings
markdown: kramdown
